/**
 * Created by jiazhen on 2016/8/18.
 */
define([], function () {
    return {
        //字段类型
        fieldType: {
            birthday: 'DATE',
            rideDate: 'DATE',
            registerTime: 'DATE',
            caseDate: 'DATE',
            seizedDate: 'DATE',
            catchDate: 'DATE',
            catchUnitDate: 'DATE',
            escapeDate: 'DATE',
            wantedDate: 'DATE',
            confirmFugitiveDate: 'DATE',
            inDetentionDate: 'DATE',
            outDetentionDate: 'DATE',
            toLocalDate: 'DATE',
            tempResSignDate: 'DATE',
            time: 'DATE',
            senderDate: 'DATE',
            outTime: 'DATETIME',
            arrivalTime: 'DATETIME',
            inTime: 'DATETIME',
            upperTime: 'DATETIME',
            floorTime: 'DATETIME',
            registrationTime: 'DATETIME',
            downTime: 'DATETIME',
            accounTime: 'DATETIME',
            transferTime: 'DATETIME',
            storageTime: 'DATETIME',
            putRecordTime: 'DATETIME',
            undoDate: 'DATETIME',
            alarmTime: 'DATETIME',
            commitDate: 'DATETIME',
            startTime: 'DATETIME',
            reserveTime: 'DATETIME',
            outDate: 'DATETIME',
            orderTime: 'DATETIME',
            videoTime: 'DATETIME',
            elapsedTime: 'DATETIME',
            rewardAmount: 'FLOAT',
            crimeNums: 'INT',
            deathNums: 'INT',
            injuredNumbers: 'INT',
            lossValue: 'INT',
            calledDuration: 'INT'
        },
        //类型输入提示
        typeTips: {
            DATE: '允许格式:yyyy-MM-dd，填写两个值时表示范围',
            DATETIME: '允许格式:yyyy-MM-dd HH:mm:ss，填写两个值时表示范围',
            FLOAT: '可填写小数（小数点后最多两位）；填写两个值时表示范围',
            INT: '只能输入整数；填写两个值时表示范围'
        },
        //字符串字段提示
        referenceDirectory: {
            name: ['不超过20个字', 20, /^([\u4e00-\u9fa5]+|([a-zA-Z]+\s?)+)$/, ['任芡淑', '速8酒店（丁墙路）', '新世纪大酒店路口']],
            idcardNo: ['请输入身份证号码', 18, /^\d{15}(\d{2}(\d|x))?$/i, '320114199110114172'],
            mobile: ['请输入手机号', 11, /^1\d{10}$/, '15905818221'],
            email: ['请输入邮箱地址', 200, /^(\w)+(\.\w+)*@(\w)+((\.\w{2,3}){1,3})$/, 'ws5AAV299@ask.com'],
            address: ['非全数字,不超过50个字', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '江苏省南京市雨花台区中华新村104号'],
            number: ['两种格式:1.首字母中文，最多4位数字 2.全数字,最长6位', 6, /^[a-zA-Z0-9]+$/, 'K1322'],
            nameCn: ['只允许中文', 200, /^([\u4e00-\u9fa5]+)$/, '任芡淑'],
            nameEn: ['只允许英文', 200, /^(([a-zA-Z]+\s?)+)$/, 'Einstein'],
            flightNo: ['允许字母数字,最多6位', 6, /^[a-zA-Z0-9]+$/, 'CZ3514'],
            boarding: ['允许字母数字', 20, /^[a-zA-Z0-9]+$/, 'CZ3514154'],
            hotelName: ['允许中文丶字母丶数字', 32, /^[a-zA-Z0-9\u4e00-\u9fa5]+$/, '速8酒店（丁墙路）'],
            inHomeAddress: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '江苏省南京市雨花台区中华新村104号'],
            inRoomNo: ['允许字母数字,不超过8位', 8, /^[a-zA-Z0-9]+$/, '43'],
            hotelAddress: ['不允许全数字', 200, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '南京市雨花台区玉兰路99号明发广场C3区3楼'],
            caseCode: ['第一位字母，18位数字', 20, /^[a-zA-Z][0-9]{17,18}$/, 'J3200000000000000025'],
            caseName: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/, '某某入室抢劫案'],
            recieveUnit: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            caseWhere: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            caseGoods: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            mType: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            brand: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            personName: ['允许中文和字母', 200, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            caseInfoSource: ['不允许全数字和特殊字符,不超过32位；', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            putRecordUnit: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '秦淮区公安局'],
            crimeOpportunity: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            crimePlace: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            crimeObject: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            crimeGoods: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            crimeMeans: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            crimeFeature: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            crimeTools: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            carNo: ['请填写车牌号', 7, /^[\u4E00-\u9FA5][\da-zA-Z]{6}$/, '苏ACX246'],
            possessor: ['允许中文或字母,不超过20位', 20, /^([\u4e00-\u9fa5]+|([a-zA-Z]+\s?)+)$/, '任芡淑'],
            carCode: ['17位，数字字母；', 17, /^[a-zA-Z0-9]{17}$/],
            telephone: ['手机号或座机验证', 15, /^(((0\d{2,3}-?)?\d{7,8})|(1\d{10}))$/, '15905818221'],
            netbar: ['允许中文或字母,不超过20位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '阙爽网络休闲会所'],
            accountName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            cardNo: ['全数字,13~19位', 19, /^\d{13,19}$/, '622898331264124298'],
            outName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            outNo: ['全数字,13~19位', 19, /^\d{13,19}$/, '622898331264124298'],
            inName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '41296383222350938'],
            inNo: ['全数字,13~19位', 19, /^\d{13,19}$/, '谷朋'],
            engineNo: ['7位或8位字母数字组合', 8, /^[a-zA-Z0-9]{7,8}$/],
            carriageNo: ['17位字母和数字组合', 17, /^[a-zA-Z0-9]{17}$/],
            label: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            reporter: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            reportermobile: ['手机号码或座机号码', 15, /^(((0\d{2,3}-?)?\d{7,8})|(1\d{10}))$/, '15905818221'],
            vehicleType: ['中文,不超过32位', 32, /^[\u4e00-\u9fa5]+$/, '中型轿车'],
            recordCode: ['字母和数字组合,不超过32位', 32, /^[a-zA-Z0-9]+$/],
            idcarNo: ['身份证号校验', 18, /^\d{15}(\d{2}(\d|x))?$/i, '622898331264124298'],
            putRecordPlace: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '江苏省南京市'],
            contactorName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            contactorTel: ['手机号码或座机号码', 15, /^(((0\d{2,3}-?)?\d{7,8})|(1\d{10}))$/],
            seizedAddress: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '江苏省南京市'],
            seizedUnit: ['不允许全数字和特殊字符,不超过32位', 32, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '秦淮区公安局'],
            calledNo: ['字母数字组合,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, 'J3200000000000000025'],
            alarmCall: ['手机号码或座机号码', 15, /^(((0\d{2,3}-?)?\d{7,8})|(1\d{10}))$/, '15905818221'],
            alarmPerson: ['允许中文或字母，不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            alarmAddress: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '江苏省南京市玄武区新街口街道85路362号'],
            alarmType: ['中文,不超过32位', 32, /^[\u4e00-\u9fa5]+$/, '经济案件类警情'],
            calledPersonNo: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            fugitiveID: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            catchWay: ['允许中文字母数字,不超过20位', 20, /^[a-zA-Z0-9\u4e00-\u9fa5]+$/, '外地公安机关协助抓获'],
            handOverDetailAddr: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            personNo: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            caseType: ['中文,不超过30位', 30, /^[\u4e00-\u9fa5]+$/, '入室抢劫案'],
            involvedLevel: ['数字,不超过2位', 2, /^\d+$/],
            fugitiveType: ['中文,不超过30位', 30, /^[\u4e00-\u9fa5]+$/, '刑拘在逃'],
            escapeCountryRegion: ['中文,不超过20位', 20, /^[\u4e00-\u9fa5]+$/, '江西省'],
            legalFormalitiesNo: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            domesticWantedCode: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            internationWantedCode: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            wantedUnitName: ['不允许全数字,不允许特殊字符，不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            putRecordUnitName: ['不允许全数字,不允许特殊字符，不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            organizer: ['不允许全数字,不允许特殊字符，不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            convictId: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            identity: ['中文,不超过50位', 50, /^[\u4e00-\u9fa5]+$/, '工人'],
            specialIdentity: ['中文,不超过50位', 50, /^[\u4e00-\u9fa5]+$/, '保安警卫'],
            detentionPeriod: ['中文,不超过20位 格式:1.xx年xx月 2.xx月 3.终身', 20, false, '30年9个月'],
            outDetentionDestination: ['不允许全数字,特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            detentionCode: ['数字,不超过20位', 20, /^\d+$/],
            accomplice: ['中文,不超过50位', 50, /^[\u4e00-\u9fa5]+$/],
            allegedCrimes: ['中文,不超过50位', 50, /^[\u4e00-\u9fa5]+$/],
            criminalID: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/],
            bridewell: ['中文,不超过50位', 50, /^[\u4e00-\u9fa5]+$/],
            bridewellNo: ['字母数字组合,不超过30位', 30, /^[a-zA-Z0-9]+$/],
            fingerprint: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/, '320104'],
            accountNo: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/, 'HNJ0000033708'],
            tempResidenceNo: ['字母数字组合,不超过20位', 20, /^[a-zA-Z0-9]+$/, 'JS00000004'],
            homeownerName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            homeowneRs: ['中文,不超过20位', 20, /^[\u4e00-\u9fa5]+$/],
            nowProfessional: ['非全数字,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            tempAddress: ['非全数字,不超过255位', 255, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '江苏省南京市秦淮区双塘街道68路903号'],
            otherCertificateno: ['字母或数字,不允许超过50位', 50, /^[a-zA-Z0-9]+$/],
            fingerPrintNo: ['数字,不允许超过20位', 20, /^\d+$/, '320104'],
            usedName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/],
            addressDetail: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            birthPlace: ['不允许全数字和特殊字符,不超过50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/],
            lonLat: ['经纬度为浮点数,经纬度之间以逗号(英文)分隔', 200, /^[+-]?\d*.\d*,[+-]?\d*.\d*$/, '118.840404，31.965982'],
            btsId: ['字母数字组合,不超过32位', 32, /^[a-zA-Z0-9]+$/, '4600151fed290801'],
            calling: ['手机号码验证', 11, /^1\d{10}$/, '15905818221'],
            called: ['手机号码验证', 11, /^1\d{10}$/, '15905818221'],
            senderName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            senderTel: ['手机号码验证', 11, /^1\d{10}$/, '15905818221'],
            senderAddress: ['不允许全数字和特殊字符,最多50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '花台区板桥新城95路392号'],
            recipientsName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            recipientsTel: ['手机号码验证', 11, /^1\d{10}$/, '15905818221'],
            recipientsAddress: ['不允许全数字和特殊字符,最多50位', 50, /^(?!\d+$)[\da-zA-Z\u4e00-\u9fa5]*$/, '花台区板桥新城95路392号'],
            passengerName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            certificateNumber: ['非中文,非特殊字符,不超过20位', 20, /^[a-zA-Z0-9]+$/, '320114199110114172'],
            userName: ['非中文,非特殊字符,不超过20位', 20, /^[a-zA-Z0-9]+$/, '15905818221'],
            realName: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            orderIdcardNo: ['身份证验证', 18, /^\d{15}(\d{2}(\d|x))?$/i, '320114199110114172'],
            orderMobile: ['手机验证', 11, /^1\d{10}$/, '15905818221'],
            orderTel: ['座机验证', 15, /^((0\d{2,3}-?)?\d{7,8})$/],
            orderemail: ['邮箱验证', 200, /^(\w)+(\.\w+)*@(\w)+((\.\w{2,3}){1,3})$/, 'ws5AAV299@ask.com'],
            tickNo: ['字母数字组合,不超过3位', 3, /^[a-zA-Z0-9]+$/],
            barCode: ['字母数字组合,不超过64位', 64, /^[a-zA-Z0-9]+$/],
            serialNo: ['数字,不超过10位', 10, /^\d+$/],
            contact: ['允许中文或字母,不超过20位', 20, /^[a-zA-Z\u4e00-\u9fa5]+$/, '任芡淑'],
            boardCardNo: ['字母数字组合,不超过10位', 10, /^[a-zA-Z0-9]+$/, 'CZ3514154'],
            loginAccount: ['不允许中文,不超过20位', 20, false, '13508182383'],
            passengerTel: ['手机号验证', 11, /^1\d{10}$/, '15905818221'],
            code: ['12位数字字符', 12, /^\d{12}$/, '000117008003'],
            type: ['允许中文和字母和数字,不超过32位', 32, /^[0-9a-zA-Z\u4e00-\u9fa5]+$/, '入室抢劫案'],
            inCity: ['中文,不超过20位', 20, /^[0-9a-zA-Z\u4e00-\u9fa5]+$/, '广州'],
            outCity: ['中文,不超过20位', 20, /^[0-9a-zA-Z\u4e00-\u9fa5]+$/, '南京'],
            carType: ['中文,不超过20位', 20, /^[0-9a-zA-Z\u4e00-\u9fa5]+$/, '中型轿车']
        },
        //资源下属字段
        dataFilter: {
            A001001: {
                name: '姓名',
                idcardNo: '身份证号码',
                birthday: '出生日期',
                mobile: '手机号码',
                email: '邮箱地址',
                address: '家庭住址'
            },
            A002001: { //!
                name: '姓名',
                idcardNo: '身份证号码',
                number: '车次',
                rideDate: '乘车日期',
                outTime: '出发时间',
                // outLon: '起点经度',
                // outLat: '起点纬度',
                // inLon: '终点经度',
                // inLat: '终点纬度',
                arrivalTime: '到达时间',
                outCity: '出发城市',
                inCity: '到达城市'
            },
            A003001: { //!
                nameCn: '中文名',
                // nameEn: '英文名',
                idcardNo: '身份证号码',
                flightNo: '航班号',
                rideDate: '航班日期',
                boarding: '登机牌号',
                outTime: '出发时间',
                // outLon: '起点经度',
                // outLat: '起点纬度',
                // inLon: '终点经度',
                // inLat: '终点纬度',
                arrivalTime: '到达时间',
                outCity: '出发城市',
                inCity: '到达城市'
            },
            A004001: { //!
                name: '姓名',
                idcardNo: '身份证号码',
                number: '车次',
                rideDate: '乘车日期',
                outTime: '出发时间',
                // outLon: '起点经度',
                // outLat: '起点纬度',
                // inLon: '终点经度',
                // inLat: '终点纬度',
                arrivalTime: '到达时间',
                outCity: '出发城市',
                inCity: '到达城市'
            },
            A005001: {
                name: '姓名',
                idcardNo: '身份证号码',
                hotelName: '酒店名称',
                // inHomeAddress: '入住人家庭地址',
                inCity: '入住城市',
                inTime: '入住时间',
                inRoomNo: '入住房号',
                outTime: '退房时间',
                hotelAddress: '酒店地址'
            },
            /*A006001: {
             caseCode: '案事件编号',
             caseName: '案件名',
             type: '案件类型',
             upperTime: '案件上限时间',
             floorTime: '案件下限时间',
             recieveUnit: '受理单位',
             caseWhere: '案发地点',
             // caseLocaleMain: '案发地点省市县',
             // caseLocaleSub: '案发地点街道',
             // caseLocaleDoorplate: '案发地点门牌',
             // caseWhereDistricts: '发案地区划',
             caseGoods: '涉案物品名称',
             // mType: '物品主类型',
             // vType: '物品副类型',
             colour: '颜色',
             brand: '品牌',
             personName: '涉案人姓名',
             idcardNo: '涉案人身份证号',
             // province: '省',
             // city: '城市',
             // liveStreet: '街道',
             caseInfoSource: '案事件信息来源',
             // caseDeputyCategory1: '副案别1',
             putRecordUnit: '立案单位',
             crimeNums: '作案人数',
             crimeOpportunity: '选择时机',
             crimePlace: '选择处所',
             crimeObject: '选择对象',
             crimeGoods: '选择物品',
             crimeMeans: '作案手段',
             crimeFeature: '作案特点',
             crimeTools: '作案工具',
             deathNums: '死亡人数',
             injuredNumbers: '受伤人数',
             lossValue: '损失价值'
             // specialCaseFlag: '专案标识'
             },*/
            A007001: { //!
                possessor: '机动车所有人',
                idcardNo: '身份证号码',
                carNo: '车牌号码',
                // carCode: '车辆识别代号',
                telephone: '联系电话',
                registerTime: '初次登记日期',
                carType: '车辆类型'
            },
            A008001: {
                netbar: '上网服务场所',
                name: '姓名',
                idcardNo: '身份证号码',
                registrationTime: '登记时间',
                downTime: '下线时间',
                address: '地址'
            },
            A009001: {
                accountName: '开户名',
                cardNo: '卡号',
                accounTime: '开户日期',
                idcardNo: '开户人身份证号',
                mobile: '开户人电话'
            },
            A010001: {
                outName: '转账人姓名',
                outNo: '转出账号',
                inNo: '转入账号',
                inName: '收款人姓名',
                transferTime: '转账时间'
            },
            A011001: {
                // engineNo: '发动机号',
                // carriageNo: '车架号',
                // carBodyColor: '车身颜色',
                // label: '厂牌型号',
                carNo: '车牌号码',
                reporter: '报案人',
                reportermobile: '报案人联系电话',
                vehicleType: '车辆种类',
                // storageTime: '入库时间',
                // recordCode: '记录编号',
                caseDate: '发案日期', //!date还是datetime
                putRecordTime: '立案时间',
                idcarNo: '车主身份证号',
                putRecordPlace: '立案地区',
                putRecordUnit: '立案单位',
                // contactorName: '办案联络人',
                // contactorTel: '办案联络人电话',
                seizedDate: '查获日期',
                seizedAddress: '查获地区',
                seizedUnit: '查获单位',
                undoDate: '撤销时间'
            },
            A012001: {
                calledNo: '接警编号',
                alarmTime: '报警时间',
                alarmCall: '报警电话',
                // calledDuration: '通话时长',
                alarmPerson: '报警人',
                alarmAddress: '报警人所处位置',
                alarmType: '报警类型',
                address: '事发地址'
                /*,
                 calledPersonNo: '接警人警号'*/
            },
            A013001: {
                caseCode: '案件编号',
                // fugitiveID: '人员编号',
                idcardNo: '公民身份证号',
                catchDate: '抓获日期',
                catchWay: '抓获方式'
                /*,
                 catchUnitDate: '抓获单位移交日期',
                 handOverDetailAddr: '移交地详细地址'*/
            },
            A014001: {
                // personNo: '人员编码',
                idcardNo: '公民身份证号',
                caseCode: '案件编号',
                caseType: '案件类型',
                // involvedLevel: '涉案级别',
                fugitiveType: '在逃类型',
                escapeDate: '逃跑日期',
                // escapeDomestic: '逃跑国内省（市）',
                escapeCountryRegion: '逃跑国家或地区'
                /*,
                 legalFormalitiesNo: '法律手续编号',
                 rewardAmount: '奖励金额',
                 wantedDate: '通缉日期',
                 domesticWantedCode: '国内通缉编号',
                 internationWantedCode: '国际通缉编号',
                 wantedUnitName: '通缉单位名称',
                 confirmFugitiveDate: '确定在逃人员日',
                 putRecordUnitName: '立案单位名称',
                 organizer: '主办单位',
                 contactorName: '联系人姓名',
                 contactorTel: '联系人电话',
                 undoDate: '撤销时间'*/
            },
            A015001: {
                // convictId: '人员编号',
                idcardNo: '身份证号码',
                identity: '身份',
                specialIdentity: '特殊身份',
                inDetentionDate: '入所日期',
                detentionPeriod: '关押期限',
                // outDetentionDestination: '出所去向',
                // outDetentionDate: '出所日期',
                caseType: '案件类型'
                /*,
                 detentionCode: '看守所编码',
                 accomplice: '同案人员',
                 allegedCrimes: '涉嫌罪名'*/
            },
            A016001: {
                criminalID: '人员编号',
                idcardNo: '身份证号',
                bridewell: '管辖所',
                bridewellNo: '科所队号',
                fingerprint: '指纹编号',
                commitDate: '提交时间'
            },
            A017001: {
                accountNo: '户号',
                tempResidenceNo: '暂住证编号',
                homeownerName: '房主姓名',
                // homeowneRs: '与房主关系',
                idcardNo: '身份证号码',
                toLocalDate: '来本地日期',
                // nowProfessional: '现从事职业',
                tempAddress: '暂住地址详址',
                tempResSignDate: '暂住证签发日期'
            },
            A018001: {
                idcardNo: '身份证号码',
                accountNo: '户号',
                // otherCertificateno: '其他证件号码',
                fingerPrintNo: '指纹编号',
                email: '电子邮箱'
            },
            A019001: {
                name: '姓名',
                usedName: '曾用名',
                birthday: '出生日期',
                addressDetail: '住址详址',
                birthPlace: '出生地',
                idcardNo: '身份证号'
            },
            C001001: {
                carNo: '车牌号码',
                time: '时间',
                lonLat: '经纬度'
            },
            C002001: {
                btsId: '基站ID号',
                calling: '主叫',
                called: '被叫',
                startTime: '通话开始时间'
            },
            C004001: {
                senderName: '寄件人姓名',
                senderTel: '寄件人电话',
                senderAddress: '寄件人地址',
                senderDate: '邮寄日期',
                recipientsName: '收件人姓名',
                recipientsTel: '收件人电话',
                recipientsAddress: '收件人地址'
            },
            C006001: {
                // reserveTime: '订票/售票时间',
                passengerName: '乘车人姓名',
                certificateNumber: '证件号码',
                rideDate: '发车日期',
                userName: '注册账号',
                realName: '注册人姓名',
                orderIdcardNo: '订票人证件号',
                orderMobile: '订票人手机',
                // orderTel: '订票人座机',
                orderemail: '订票人邮箱'
                /*,
                 tickNo: '票号',
                 barCode: '输入条形码',
                 serialNo: '流水号'*/
            },
            C010001: {
                name: '店名',
                address: '店址',
                mobile: '联系人电话',
                contact: '联系人'
            },
            C013001: {
                flightNo: '航班号',
                rideDate: '航班日期',
                idcardNo: '证件号',
                boardCardNo: '登机牌号',
                mobile: '联系电话'
            },
            C014001: {
                loginAccount: '登录账号',
                idcardNo: '乘客证件号码',
                passengerTel: '乘客手机号',
                flightNo: '航班号',
                outDate: '起始时间',
                inTime: '目的时间',
                orderTime: '订单时间'
            },
            D001001: {
                videoTime: '视频时间',
                carNo: '车牌号码'
            },
            D002001: {
                code: '卡口编号',
                name: '卡口名称',
                carNo: '车辆号码',
                elapsedTime: '经过时间'
                /*,
                 lonLat: '经纬度'*/
            }
        }
    };
});
